---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testdaemonset
  namespace: testnamespace
  labels:
    app: testdaemon
spec:
  selector:
    matchLabels:
      name: testdaemon
  template:
    metadata:
      labels:
        name: testdaemon
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
