---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: testdaemonset
  namespace: testnamespace
spec:
  spec:
    containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
