---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: testreplicaset
  labels:
    app: testapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testpod
          image: nginx:1.14.2
          ports:
            - containerPort: 80
