---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: testreplicaset
  labels:
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: testpod
          image: nginx:1.14.2
          ports:
            - containerPort: 80
